# Generated by Django 5.1.3 on 2026-01-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_customuser_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
