# Generated by Django 5.1.3 on 2026-01-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approval_user',
            field=models.BooleanField(default=False),
        ),
    ]
