# Generated by Django 5.1.3 on 2026-02-23 13:06

import a_core.utils.storage
import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_is_approval_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=a_core.utils.storage.OverwriteStorage(), upload_to=account.models.CustomUser._get_image_url),
        ),
    ]
