# Generated by Django 5.1.3 on 2026-02-23 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0001_initial'),
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_app.payment'),
        ),
    ]
