# Generated by Django 5.1.3 on 2026-01-21 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
        ('request_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='proposed_by',
        ),
        migrations.RemoveField(
            model_name='request',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='requestmessage',
            name='request',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaigns', to='request_app.request'),
        ),
        migrations.RemoveField(
            model_name='requestmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='RequestMessage',
        ),
    ]
