# Generated by Django 5.1.3 on 2026-01-12 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='gallery_urls',
        ),
        migrations.AlterField(
            model_name='schemeimages',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='campaign.scheme'),
        ),
    ]
