# Generated by Django 5.1.3 on 2026-01-25 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_remove_request_proposed_by_and_more'),
        ('request_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign', to='request_app.request'),
        ),
    ]
