# Generated by Django 5.1.3 on 2026-01-13 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_remove_scheme_gallery_urls_alter_schemeimages_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schemes', to='campaign.request'),
        ),
    ]
