# Generated by Django 5.1.3 on 2026-01-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_alter_request_request_end_date_alter_scheme_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='cover_image_url',
            new_name='cover_image',
        ),
    ]
