# Generated by Django 5.1.3 on 2026-01-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_alter_campaign_request'),
        ('request_app', '0002_request_requested_for_request_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='campaign',
            name='campaign_ca_status_dc625a_idx',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='status',
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['visibility'], name='campaign_ca_visibil_9aee10_idx'),
        ),
    ]
