# Generated by Django 5.1.3 on 2026-02-23 13:06

import a_core.utils.storage
import campaign.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_remove_campaign_campaign_ca_status_dc625a_idx_and_more'),
        ('request_app', '0004_rename_massges_requestmessage_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=a_core.utils.storage.OverwriteStorage(), upload_to=campaign.models.Campaign._get_image_url),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_obj', to='request_app.request'),
        ),
    ]
