# Generated by Django 5.1.3 on 2026-05-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_customeauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='MembershipRequest',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
