# Generated by Django 5.2.14 on 2026-05-25 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['raised_by', 'status'], name='expenses_ex_raised__e87e96_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', '-created_at'], name='expenses_ex_status_e52e40_idx'),
        ),
    ]
