# Generated by Django 6.0.5 on 2026-05-14 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('role', 'Role Management'), ('expense', 'Expense'), ('payment', 'Payment'), ('donation', 'Donation'), ('notice', 'Notice'), ('approval', 'Approval'), ('order', 'Order'), ('ngo', 'NGO Request'), ('system', 'System')], default='system', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dashboard_a_user_id_fec774_idx'), models.Index(fields=['category', '-created_at'], name='dashboard_a_categor_26840d_idx')],
            },
        ),
    ]
