# Generated by Django 5.1.3 on 2026-01-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requested_for',
            field=models.CharField(choices=[('CAMPAIGN', 'Campaign')], db_index=True, default='CAMPAIGN', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('CANCEL', 'Cancel'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
