# Generated by Django 5.1.3 on 2026-01-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0002_request_requested_for_request_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request_end_date',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='request_start_date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('CANCELED', 'Canceled'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
