# Generated by Django 5.1.3 on 2026-01-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0003_rename_request_end_date_request_last_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestmessage',
            old_name='massges',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='request',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
