# Generated by Django 5.2.14 on 2026-05-25 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['is_approved', 'is_active', '-created_at'], name='notices_not_is_appr_eefc34_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['expires_at'], name='notices_not_expires_179ee9_idx'),
        ),
    ]
