# Generated by Django 6.0.5 on 2026-05-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
