# Generated by Django 5.2.14 on 2026-05-25 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fundrequest',
            index=models.Index(fields=['status', '-created_at'], name='ngo_request_status_a11b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='fundrequest',
            index=models.Index(fields=['ngo_user', 'status'], name='ngo_request_ngo_use_03d5a7_idx'),
        ),
    ]
