# Generated by Django 5.1.3 on 2026-03-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='requested_for',
            new_name='payment_for',
        ),
    ]
