# Generated by Django 5.2.14 on 2026-05-25 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_rolerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rolerequest',
            index=models.Index(fields=['user', 'status'], name='roles_roler_user_id_f18e49_idx'),
        ),
        migrations.AddIndex(
            model_name='rolerequest',
            index=models.Index(fields=['status', '-created_at'], name='roles_roler_status_a2f571_idx'),
        ),
    ]
