import re

from locust import TaskSet, task


class AuthenticatedBehavior(TaskSet):
    """Simulates a logged-in member: donations, expenses, profile, notices."""

    USERNAME = "loadtest_user"
    PASSWORD = "LoadTest_Pass123!"

    def on_start(self):
        self._login()

    def _login(self):
        login_page = self.client.get("/auth/login/", name="Login Page (auth)")
        csrf = self._extract_csrf(login_page.text)
        response = self.client.post(
            "/auth/login/",
            data={
                "username": self.USERNAME,
                "password": self.PASSWORD,
                "csrfmiddlewaretoken": csrf,
            },
            headers={"Referer": self.client.base_url + "/auth/login/"},
            name="Login Submit",
        )
        if response.status_code != 200 or "login" in response.url:
            response.failure("Login failed")

    def _extract_csrf(self, html):
        match = re.search(r'name="csrfmiddlewaretoken" value="([^"]+)"', html)
        return match.group(1) if match else ""

    @task(5)
    def view_home(self):
        self.client.get("/", name="Home (auth)")

    @task(4)
    def view_donations_list(self):
        self.client.get("/donations/", name="Donations List")

    @task(3)
    def view_donation_add_page(self):
        self.client.get("/donations/add/", name="Donation Add Form")

    @task(2)
    def submit_donation(self):
        page = self.client.get("/donations/add/", name="Donation Add (pre-submit)")
        csrf = self._extract_csrf(page.text)
        self.client.post(
            "/donations/add/",
            data={
                "donor_name": "Load Test Donor",
                "amount": "100.00",
                "donation_type": "general",
                "description": "Load test donation",
                "csrfmiddlewaretoken": csrf,
            },
            headers={"Referer": self.client.base_url + "/donations/add/"},
            name="Donation Submit",
        )

    @task(3)
    def view_expenses_list(self):
        self.client.get("/expenses/", name="Expenses List")

    @task(2)
    def view_expense_create_page(self):
        self.client.get("/expenses/create/", name="Expense Create Form")

    @task(1)
    def submit_expense(self):
        page = self.client.get("/expenses/create/", name="Expense Create (pre-submit)")
        csrf = self._extract_csrf(page.text)
        self.client.post(
            "/expenses/create/",
            data={
                "title": "Load test expense",
                "description": "Generated by load test",
                "amount": "50.00",
                "category": "office",
                "csrfmiddlewaretoken": csrf,
            },
            headers={"Referer": self.client.base_url + "/expenses/create/"},
            name="Expense Submit",
        )

    @task(3)
    def view_profile(self):
        self.client.get("/auth/profile/", name="Profile")

    @task(2)
    def view_notices(self):
        self.client.get("/notices/", name="Notices (auth)")

    @task(1)
    def view_products(self):
        self.client.get("/products/", name="Products")

    @task(1)
    def view_chat_groups(self):
        self.client.get("/chat/", name="Chat Groups")
