# Generated by Django 6.0.5 on 2026-05-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_name', models.CharField(default='Trust Management System', max_length=200)),
                ('trust_description', models.TextField(blank=True)),
                ('membership_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user_join_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_donation_amount', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('meta_title', models.CharField(blank=True, default='Trust Management', max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('razorpay_key_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_key_secret', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
